name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Auto-reload on pushes to the main branch.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install PythonAnywhere CLI
      run: |
        pip install --upgrade pip
        pip install pythonanywhere  # Install the PythonAnywhere CLI tool.

    - name: Deploy Django App to PythonAnywhere
      env:
        PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        PA_USERNAME: ${{ secrets.PA_USERNAME }}
      run: |
        # Export PythonAnywhere API token
        export PYTHONANYWHERE_API_TOKEN=${PA_API_TOKEN}

        # Reload the web app on PythonAnywhere
        curl -X POST "https://www.pythonanywhere.com/api/v0/user/${PA_USERNAME}/webapps/${PA_USERNAME}.pythonanywhere.com/reload/" \
          -H "Authorization: Token ${PA_API_TOKEN}"